In [8]:
import pandas as pd
df = pd.read_csv('text.csv')
df2 = pd.read_csv('text2.csv')
df3 = pd.read_csv('text3.csv')
display(df)
display(df2)
display(df3)

,ID_Pedido,Data_Venda,ID_Loja,ID_Produto,ID_Cliente,Qtd_Vendida,Receita_Venda,Custo_Venda,Custo_Unit,Preco_Unit
0,1,2019-01-01,2,4,16,1,350,129.5,129.5,350
1,2,2019-01-01,1,4,17,1,350,129.5,129.5,350
2,3,2019-01-01,3,4,23,1,350,129.5,129.5,350
3,4,2019-01-01,8,4,24,1,350,129.5,129.5,350
4,5,2019-01-01,4,4,25,1,350,129.5,129.5,350
...,...,...,...,...,...,...,...,...,...,...
369,370,2019-12-14,6,8,31,1,600,258.0,258.0,600
370,371,2019-12-14,7,8,78,1,600,258.0,258.0,600
371,372,2019-12-20,1,8,78,1,600,258.0,258.0,600
372,373,2019-12-24,4,8,4,1,600,258.0,258.0,600
373,374,2019-12-24,7,8,55,1,600,258.0,258.0,600

,ID_Produto,Nome_Produto,ID_Categoria,Marca_Produto,Num_Serie,Preco_Unit,Custo_Unit
0,1,"Monitor LED 19,5'' Full HD HDMI",1,DELL,MNT-DL-831923,2300,966.0
1,2,Monitor Curvo 24'' 144Hz HDMI,1,SAMSUNG,MNT-SS-001939,2800,980.0
2,3,Webcam Full HD 1080p,1,LOGITECH,WBC-LT-934GG4,450,90.0
3,4,Kit Teclado + Mouse sem fio Wireless,2,DELL,KTM-DL-041039,350,129.5
4,5,Kit Teclado + Mouse Slim Bluetooth,2,DELL,KTM-DL-111924,280,109.2
5,6,Cadeira Gamer reclinável Azul/Laranja,3,ALTURA,CGM-AL-9N914J,1800,540.0
6,7,Cadeira Gamer PC Racer Vermelha,3,ALTURA,CGM-AL-0147FI,3100,1395.0
7,8,Headphone Bluetooth 2000,4,SONY,HDP-SN-194821,600,258.0
8,9,Fone de Ouvido Tune T5000,4,JBL,HDP-JB-091934,780,327.6
9,10,Microfone Condensador MC1000,5,AKG,MIC-AK-237591,1100,275.0
10,11,Microfone Condensador com Tripé,5,BLUE,MIC-BL-819455,800,344.0
11,12,Microfone de mesa com fio condensador,5,BLUE,MIC-BL-761411,650,214.5
12,13,Notebook LC2100 Intel Core i5 8GB,6,SAMSUNG,NOT-SS-918457,3400,850.0
13,14,Notebook Inspiron 15 5000 4GB,6,DELL,NOT-DL-000012,3100,1209.0
14,15,Notebook IdeaPad RF32000,6,DELL,NOT-DL-77164I,4200,1176.0
15,16,Notebook Motion Ultra 2,6,SAMSUNG,NOT-SS-13139U,2900,1160.0

,ID_Loja,Loja,Gerente,Endereco,Num_Funcionarios,Telefone
0,1,Rio de Janeiro,Pedro Martins,"R. Visc. de Pirajá, 136 - Ipanema, Rio de Jane...",23,(21) 3198-1239
1,2,Belo Horizonte,Julia Freitas,"Av. Barão Homem de Melo, 1389 - Nova Granada, ...",13,(31) 2891-2394
2,3,Salvador,Marcelo Castro,"Shopping Barra - Av. Centenário, 2992 - Barra,...",19,(71) 3465-8748
3,4,Curitiba,Amanda Lima,"R. Brasílio Itiberê, 3279 - Água Verde, Curiti...",31,(41) 2923-2137
4,5,Fortaleza,Letícia Gomes,"Av. Dom Luís, 500 - Aldeota, Fortaleza - CE, 6...",12,(85) 3294-1481
5,6,São Paulo,Rogério Lopes,"R. Teodoro Sampaio, 954 - Pinheiros, São Paulo...",33,(11) 3295-3945
6,7,Niterói,Matheus Leal,"Rua Quinze de Novembro, 8 - Loja 301a Loja 301...",18,(21) 3134-7263
7,8,Goiânia,Carlos Henrique,"Av. Goiás Norte, 3.592 - quadra 2.1 - St. Mal....",11,NaN

In [9]:
df3 = df3.drop(columns=['Telefone'])
df = df.drop(columns=['Preco_Unit'])
display(df)
display(df3)
df['Faturamento_Venda'] = df['Receita_Venda'] * df['Qtd_Vendida']
display(df)

,ID_Pedido,Data_Venda,ID_Loja,ID_Produto,ID_Cliente,Qtd_Vendida,Receita_Venda,Custo_Venda,Custo_Unit
0,1,2019-01-01,2,4,16,1,350,129.5,129.5
1,2,2019-01-01,1,4,17,1,350,129.5,129.5
2,3,2019-01-01,3,4,23,1,350,129.5,129.5
3,4,2019-01-01,8,4,24,1,350,129.5,129.5
4,5,2019-01-01,4,4,25,1,350,129.5,129.5
...,...,...,...,...,...,...,...,...,...
369,370,2019-12-14,6,8,31,1,600,258.0,258.0
370,371,2019-12-14,7,8,78,1,600,258.0,258.0
371,372,2019-12-20,1,8,78,1,600,258.0,258.0
372,373,2019-12-24,4,8,4,1,600,258.0,258.0
373,374,2019-12-24,7,8,55,1,600,258.0,258.0

,ID_Loja,Loja,Gerente,Endereco,Num_Funcionarios
0,1,Rio de Janeiro,Pedro Martins,"R. Visc. de Pirajá, 136 - Ipanema, Rio de Jane...",23
1,2,Belo Horizonte,Julia Freitas,"Av. Barão Homem de Melo, 1389 - Nova Granada, ...",13
2,3,Salvador,Marcelo Castro,"Shopping Barra - Av. Centenário, 2992 - Barra,...",19
3,4,Curitiba,Amanda Lima,"R. Brasílio Itiberê, 3279 - Água Verde, Curiti...",31
4,5,Fortaleza,Letícia Gomes,"Av. Dom Luís, 500 - Aldeota, Fortaleza - CE, 6...",12
5,6,São Paulo,Rogério Lopes,"R. Teodoro Sampaio, 954 - Pinheiros, São Paulo...",33
6,7,Niterói,Matheus Leal,"Rua Quinze de Novembro, 8 - Loja 301a Loja 301...",18
7,8,Goiânia,Carlos Henrique,"Av. Goiás Norte, 3.592 - quadra 2.1 - St. Mal....",11

,ID_Pedido,Data_Venda,ID_Loja,ID_Produto,ID_Cliente,Qtd_Vendida,Receita_Venda,Custo_Venda,Custo_Unit,Faturamento_Venda
0,1,2019-01-01,2,4,16,1,350,129.5,129.5,350
1,2,2019-01-01,1,4,17,1,350,129.5,129.5,350
2,3,2019-01-01,3,4,23,1,350,129.5,129.5,350
3,4,2019-01-01,8,4,24,1,350,129.5,129.5,350
4,5,2019-01-01,4,4,25,1,350,129.5,129.5,350
...,...,...,...,...,...,...,...,...,...,...
369,370,2019-12-14,6,8,31,1,600,258.0,258.0,600
370,371,2019-12-14,7,8,78,1,600,258.0,258.0,600
371,372,2019-12-20,1,8,78,1,600,258.0,258.0,600
372,373,2019-12-24,4,8,4,1,600,258.0,258.0,600
373,374,2019-12-24,7,8,55,1,600,258.0,258.0,600

In [10]:
df.to_excel('text.xlsx', index=False)
df2.to_excel('text2.xlsx', index=False)
df3.to_excel('text3.xlsx', index=False)